import { test, expect } from '@playwright/test';

// Mock data and utilities
import { createTestTask } from '../fixtures/tasks';
import { loginAsTestUser } from '../utils/helpers';

// Define the end-to-end test suite for prompt generation

// Run these tests with the specific test user session
// Assumes user is already created and can log in
loginAsTestUser();

test.describe('Task Prompt Generation', () => {
  test('should generate prompt for task title and description', async ({ page }) => {
    // Navigate to the task creation page
    await page.goto('/project/some-project-id/task/new');

    // Fill in the task form
    await page.fill('input[name="task-title"]', 'Test Task Title');
    await page.fill('textarea[name="task-description"]', 'Test task description for end-to-end testing.');

    // Submit the form to generate a prompt
    await page.click('button:has-text("Generate Prompt")');

    // Wait for the prompt to be generated by the backend
    await page.waitForResponse(response =>
      response.url().includes('/api/tasks/generate-prompt') && response.status() === 200
    );

    // Verify that the generated prompt appears in the task form
    const promptContent = await page.textContent('div.prompt-preview');
    expect(promptContent).toContain('Generated Prompt:');
    expect(promptContent).toContain('Test Task Title');
  });
});